name: 06 - Contexts
run-name: 06 - contexts | DEBUG ${{inputs.debug}}

on:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

env: 
    MY_WORKFLOW_VAR: "workflow"
    MY_OVERWRITTEN_VAR: "overwriiten workflow"                

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: "job"
            MY_OVERWRITTEN_VAR: "overwritten job"
        steps:
            - name: Display Information
              run: |
                 echo "Event name: ${{github.event_name}}"
                 echo "Ref: ${{github.ref}}"
                 echo "SHA: ${{github.sha}}"
                 echo "Actor: ${{github.actor}}"
                 echo "Run ID: ${{github.run_id}}"
                 echo "Run number: ${{github.run_number}}"

            - name: Retrieve Variable
              run:  "echo 'Repository Variable: ${{vars.MY_VAR}}'"

            - name: Print ENV Variables
              env:
                MY_OVERWRITTEN_VAR: "step"
              run : |
                echo 'ENV Variable: ${{env.MY_WORKFLOW_VAR}}'
                echo 'Overwriiten Variable: ${{env.MY_OVERWRITTEN_VAR}}'
            - name: Print ENV Variables
              run : |
                echo 'ENV Variable: ${{env.MY_WORKFLOW_VAR}}'
                echo 'Overwriiten Variable: ${{env.MY_OVERWRITTEN_VAR}}'
