name: 09 - Using Functions

on:
    pull_request:
    workflow_dispatch:
        
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR title
              run: 'echo "PR title: ${{GitHub.event.pull_request.title}}"'

            - name: Print PR labels
              run: 'echo "PR labels: ${{toJson(GitHub.event.pull_request.labels)}}"'

            - name: Bug step
              if: ${{failure() && contains(GitHub.event.pull_request.title, 'fix')}}
              run: "I am a bug fix"

            - name: Sleep for 20 seconds
              run: sleep 20  
 
            - name: Failing Step
              run: exit 1   

            - name: I will be skipped
              if: ${{ success() }}
              run: echo "I will print if previous steps succeed."  

            - name: I will execute
              if: ${{ failure() }}
              run: "I will print if any previous step fails."  

            - name: I will execute
              if: ${{ !cancelled() }}
              run: "I will always print, except when the workflow is cancelled."  

            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: "I will execute when cancelled"  